### PR TITLE
 Make non-member functions static members.

### PR DESCRIPTION
**Pull request by lhmouse**

### CODE REVIEW

**Comment by FrankHB** [comment]
This seems hardly as "optimization" (which is about code transformation/codegen in parlance of language implementation).

**Comment by FrankHB** [comment]
Well, many instances of adding `this->` seem to have nothing to do with "make non-member functions static members"...

**Comment by lhmouse** [comment]
> This seems hardly as "optimization" (which is about code transformation/codegen in parlance of language implementation).

Please consider this a coding style 'optimization' due to lack of an appropriate category.
 
> Well, many instances of adding this-> seem to have nothing to do with "make non-member functions static members"...

_The_ convention for calling a non-static member function on the implied object requires `this->`. It wasn't there only because those functions were non-member.

**Comment by FrankHB** [comment]
> Please consider this a coding style 'optimization' due to lack of an appropriate category.

So is it better to introduce `style` category directly?

> _The_ convention for calling a non-static member function on the implied object requires `this->`. It wasn't there only because those functions were non-member.

Where is _the_ convention? The language specification mandates the order of name lookup in the class scope so lack of `this->` in several contexts would make no semantic difference. And I find no style convention or maintenance documentation to override the language rules.

**Comment by lhmouse** [comment]
在 2018/8/30 10:40, FrankHB 写道:
>     Please consider this a coding style 'optimization' due to lack of an
>     appropriate category.
> 
> So is it better to introduce |style| category directly?
> 

I used to have an idea about this, but eventually dropped it because of 
the intersection of it and `optimization` (which was `enhancement`).

>     /The/ convention for calling a non-static member function on the
>     implied object requires |this->|. It wasn't there only because those
>     functions were non-member.
> 
> Where is /the/ convention? The language specification mandates the order 
> of name lookup in the class scope so lack of |this->| in several 
> contexts would make no semantic difference. And I find no style 
> convention or maintenance documentation to override the language rules.
> 

It is primarily due to consistency and clarification of being non-static 
member function calls, because under some circumstances `this->` is 
required (e.g. when referring to the member of a base of a dependent 
name). Access to static data members and static member functions 
requires no special treatment unless otherwise required (for example, 
`std::string str; if(str.find('a') == str.npos) { ... } ` is usually 
preferred to `std::string::npos` but this isn't restrictive).

-- 
Best regards,
LH_Mouse

**Comment by lhmouse** [comment]
在 2018/8/30 11:18, FrankHB 写道:
>     I used to have an idea about this, but eventually dropped it because
>     of the intersection of it and |optimization| (which was |enhancement|).
> 
> In general, both "optimization" and "enhancement" tags in are presented 
> to users. This corresponds the tradition that issue tracking systems are 
> used to follow issues of components concerned by users, not maintainers. 
> Tags are seldom combined together to get different meaning (i.e. "style" 
> conjunct with "optimization" is not "optimization"). Either way, I don't 
> see the single use of "optimization" conveying your intention here.

If there were sort of categorization then life would be much easier... Sad.

**optimization** means 'something that does not add or remove 
interfaces' (well we are at pre-alpha so the difference is trivial).  If 
something gets added or removed then this goes into the 
**feature-request** category.

> 
>     It is primarily due to consistency and clarification of being
>     non-static member function calls, because under some circumstances
>     |this->| is required (e.g. when referring to the member of a base of
>     a dependent name).
> 
> I have no comment about the style itself (except that I do know it and I 
> don't use it for simplicity of having less overriding rules from the 
> base specification), but the lack of specification is somewhat 
> problematic. Though I see the rationale quite easily, not everybody else 
> will likely do.
>

There is always style disagreement - there might be more or less, but it 
is its presence that we cannot eliminate.

>     Access to static data members and static member functions requires
>     no special treatment unless otherwise required (for example,
>     |std::string str; if(str.find('a') == str.npos) { ... }| is usually
>     preferred to |std::string::npos| but this isn't restrictive).
> 
> I'm permissive on that on the contrary direction. To me, |str.npos| 
> means that "I don't worry whether |npos| is a static member or not", 

WRT 'good styles', if something **has** to be a non-static member then 
it **shall** always be.

> while |string::npos| /requires/ |npos| is a name of a static member 
> (knowing |string| is not a namespace name). This would particularly 
> significant in generic code, and I tend to ease the life to the simpler 
> convention: use |::| first, if possible.
> 
>

This code is not generic so what you said does not apply. Generic code 
is a different story e.g. when the type of `str` can't be obtained 
directly from a template parameter then it is going to look like 
`std::decay_t<decltype(str)>::npos` which is nothing but more obscure.


-- 
Best regards,
LH_Mouse

**Comment by FrankHB** [comment]
> **optimization** means 'something that does not add or remove interfaces' (well we are at pre-alpha so the difference is trivial). If something gets added or removed then this goes into the **feature-request** category.

This seems over-fit. As mentioned in a post in std-discussion, not all bidirectional compatible changes are optimizations. At least, *pessimizations* should be distinguished alongside.

> There is always style disagreement - there might be more or less, but it is its presence that we cannot eliminate.

Yep. However, this does not eliminate the rules to clarify which direction is preferred and actually taken by a particular project. This feeds criteria to make real optimizations, or other kinds of intentions, being distinguishable. This may also decrease occasional but unintentional changes.

> This code is not generic so what you said does not apply.

Generally, taking the piece of code contextually would make it essentially "generic", due to lack of enough context information. In real life of coding I usually don't expect whether a piece of code need to be (parametric) polymorphic or not, until the typing are required to be done to make the code well-defined as per the rules of the object language (here, C++). In other words, my brain would only have resolution of (opt-in) typed code generation as a quite late stage after arbitrary type interference by real time reasoning, which has better properties of any existed type systems (by locally fabericating a new one embedding in the object language). So early evaluation to determine the existence polymorphism seems premature optimization in mind.

This would be different for macros. The code would naturally be broken anywhere if arbitrary (esp. object) macros are involved, so I would assume there is no macros by default (except well-known ones).

Such strategies do depend on coders. Nonetheless, it do have concerns observable in code, e.g. refactoring based on text, interface design based on structural typing, etc..

**Pull request merged**
